### ISSUE TITLE
No module named 'yaml'

### ISSUE THREAD

**Issue by MrPi3141** [jpetazzo/griode#12]
pi@raspberrypi:~/griode $ ./griode.py
Traceback (most recent call last):
  File "./griode.py", line 8, in <module>
    from arpeggiator import ArpConfig, Arpeggiator
  File "/home/pi/griode/arpeggiator.py", line 5, in <module>
    from gridgets import Gridget, Surface
  File "/home/pi/griode/gridgets.py", line 3, in <module>
    from palette import palette
  File "/home/pi/griode/palette.py", line 26, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

I have tried installing 'python-yaml' to no avail.

**Comment by rainnies** [comment]
Hi,
Try to install 'pyyaml'.
