### ISSUE TITLE
couldn't get it to work

### ISSUE THREAD

**Issue by CheAhMeD** [jpetazzo/griode#22]
Hello,
I followed the setup instructions in the readme but I was never able to make Griode work

Can you help please?
running it without sudo 
`./griode.py 
Traceback (most recent call last):
  File "/home/tchi/griode/./griode.py", line 189, in <module>
    main()
  File "/home/tchi/griode/./griode.py", line 176, in main
    griode = Griode()
             ^^^^^^^^
  File "/home/tchi/griode/./griode.py", line 31, in __init__
    persistent_attrs_init(self)
  File "/home/tchi/griode/persistence.py", line 36, in persistent_attrs_init
    self.db = shelve_open(self.db_filename)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tchi/griode/persistence.py", line 8, in shelve_open
    cache[filename] = shelve.open(filename, writeback=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
_dbm.error: [Errno 13] Permission denied: 'state/Griode.sav'
`

running sudo ./griode.py gives:
`sudo ./griode.py 
[INFO] fluidsynth.py:76 __init__() -> Using audio driver: alsa
fluidsynth: error: Failed to open the "default" audio device
Failed to create the audio driver. Giving up.
[INFO] fluidsynth.py:107 __init__() -> Found 0 instruments
fluidsynth: error: Failed to open the "default" audio device
Failed to create the audio driver. Giving up.
[ERROR] fluidsynth.py:139 __init__() -> Failed to locate the fluidsynth port!`

running it again with debug level:
export LOG_LEVEL=DEBUG
` sudo ./griode.py
[INFO] fluidsynth.py:76 __init__() -> Using audio driver: alsa
fluidsynth: error: Failed to open the "default" audio device
Failed to create the audio driver. Giving up.
[INFO] fluidsynth.py:107 __init__() -> Found 0 instruments
fluidsynth: error: Failed to open the "default" audio device
Failed to create the audio driver. Giving up.
[INFO] fluidsynth.py:135 __init__() -> Connected to MIDI output griode:griode 129:0
Traceback (most recent call last):
  File "/home/tchi/griode/./griode.py", line 189, in <module>
    main()
  File "/home/tchi/griode/./griode.py", line 176, in main
    griode = Griode()
             ^^^^^^^^
  File "/home/tchi/griode/./griode.py", line 33, in __init__
    self.devicechains = [DeviceChain(self, i) for i in range(16)]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tchi/griode/./griode.py", line 33, in <listcomp>
    self.devicechains = [DeviceChain(self, i) for i in range(16)]
                         ^^^^^^^^^^^^^^^^^^^^
  File "/home/tchi/griode/./griode.py", line 136, in __init__
    self.program_change()
  File "/home/tchi/griode/./griode.py", line 151, in program_change
    instrument = self.instrument
                 ^^^^^^^^^^^^^^^
  File "/home/tchi/griode/./griode.py", line 144, in instrument
    groups = fonts.get(self.font_index, fonts[0])
                                        ~~~~~^^^
KeyError: 0
`

**Comment by jpetazzo** [comment]
Hi there!

Sorry for the slow reply :)

Okay, let's see.

> `_dbm.error: [Errno 13] Permission denied: 'state/Griode.sav' `

This one is probably because the state file (`state/Griode.sav`) was created as root, and therefore, can no longer be updated as a normal user. If you want to run griode as a normal user (which should be totally possible, as long as the user is part of the right groups to access devices and such) you can do something like `chown -R $USER state` do change ownership of the state directory back to your regular user.

> `fluidsynth: error: Failed to open the "default" audio device`

Do you have a working alsa device (i.e. sound) that you can open as a user? I think that could be tested maybe with `mplayer -ao alsa some-audio-file.mp3` (for instance).

You can also force the audio driver by setting `GRIODE_AUDIO_DRIVER` to `pulseaudio` (assuming you have pulseaudio).

For now it looks like griode quits because fluidsynth failed to start (because it couldn't initialize the audio driver).

I hope this helps!
